[package]
name = "rooster"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xml-rs = "0.8.19"
serde_json = { version = "1.0.108", features = [] }
tiny_http = "0.12.0"